=== dpereira7/DAW2020/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT PR (key_name,title,subtitle,begin_date,end_date,supervisor,work_team,abstract,deliverables) >

<!ELEMENT key_name (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin_date (#PCDATA) >
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >

<!ATTLIST supervisor href CDATA #REQUIRED>


<!ELEMENT work_team (elemento)+ >

<!ELEMENT elemento (name,number,mail,site) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT number (#PCDATA) >
<!ELEMENT mail (#PCDATA) >
<!ELEMENT site (#PCDATA) >

<!ATTLIST site href CDATA #REQUIRED>


<!ELEMENT abstract (paragraph)+ >

<!ELEMENT paragraph (#PCDATA|bold|italic|underline|link)* >
<!ELEMENT bold (#PCDATA) >
<!ELEMENT italic (#PCDATA) >
<!ELEMENT underline (#PCDATA) >
<!ELEMENT link (#PCDATA) >

<!ATTLIST link href CDATA #REQUIRED >


<!ELEMENT deliverables (link)+ >

=== dpereira7/DAW2020/TPCs/TPC2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "file:/C:/Users/Diogo/Documents/Universidade/4%C2%BAAno/DAW/TP2/PR.dtd">
<PR>
    <key_name>TPC 2</key_name>
    <title>Resolução de TPC's</title>
    <subtitle>Resolução do TPC 2</subtitle>
    <begin_date>Outubro 2020</begin_date>
    <end_date>Outubro 2020</end_date>
    <supervisor href="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    <work_team>
        <elemento>
            <name>Diogo Paulo da Costa Pereira</name>
            <number>84092</number>
            <mail>a84092@uminho.pt</mail>
            <site href="http://www.github.com/dpereira7/DAW2020">www.github.com/dpereira7/DAW2020</site>
        </elemento>
    </work_team>
    <abstract>
        <paragraph>Resolução deo TPC número 2.</paragraph>
        <paragraph>O TPC contempla um ficheiro dtd e um ficheiro xml.</paragraph>
    </abstract>
    <deliverables>
        <link href="PR.dtd">Report(DTD version)</link>
        <link href="PR.xml">Report(XML version)</link>
    </deliverables>
</PR>

=== dpereira7/DAW2020/TPCs/TPC3/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "file:/C:/Users/Diogo/Documents/Universidade/4%C2%BAAno/DAW/TP2/PR.dtd">
<PR>
    <key_name>XSL</key_name>
    <title>Resolução de TPC's</title>
    <subtitle>Resolução do TPC 3</subtitle>
    <begin_date>Outubro 2020</begin_date>
    <end_date>Outubro 2020</end_date>
    <supervisor href="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    <work_team>
        <elemento>
            <name>Diogo Paulo da Costa Pereira</name>
            <number>84092</number>
            <mail>a84092@uminho.pt</mail>
            <site href="http://www.github.com/dpereira7/DAW2020">www.github.com/dpereira7/DAW2020</site>
        </elemento>
    </work_team>
    <abstract>
        <paragraph>Resolução do TPC número 3.</paragraph>
        <paragraph>Geração de Website com transformações XSL.</paragraph>
        <paragraph>O TPC contempla uma pasta com os ficheiros do website desenvolvido,um ficheiro dtd, um ficheiro xml e um ficheiro xsl.</paragraph>
    </abstract>
    <deliverables>
        <link href="site">Folder(Site pages)</link>
        <link href="PR.xml">Report(XML version)</link>
        <link href="ArqSite.dtd">Report(DTD version)</link>
        <link href="arq.xml">DataSet</link>
        <link href="arqSite.xsl">Report(XSL version)</link>
    </deliverables>
</PR>
